### ISSUE TITLE
Update v0.9 to its dev branch to solve known dependecy issue

### ISSUE THREAD

**Issue by devparticle** [Xilinx/finn#1069]
Because of ongoing issue with step_hw_ipgen in v0.10, I decided to go back to v0.9. But then I remembered I was using dev branch of v0.9 because of a known dependency issue. But now I cant install the dev version of v0.9 since only the official release is available to clone and I cant use v0.10 as the issue is still being looked into. Is it possible to update v0.9 to solve the dependency issue? [https://github.com/Xilinx/finn/issues/870](url)

**Comment by auphelia** [comment]
Hi @devparticle, 

You can always checkout certain commit versions of finn and then start the Docker container from there.
e.g.
`git clone https://github.com/Xilinx/finn.git` 
`git checkout a4c15df9964cfb6f7e83e6e52316b7e59758ceb6`
`bash run-docker.sh`

You can look up the history of each branch in the list of commits, e.g. of the `main` branch here: https://github.com/Xilinx/finn/commits/main/

I am closing this issue, because I think this should solve your problem. Please feel free to reopen.
