### ISSUE TITLE
Check if sorted before InferDataTypes

### ISSUE THREAD

**Issue by Tobi-Alonso** [Xilinx/finn#164]
`InferDataTypes` can fail is the graph is not sorted.
Usually, in `CustomOp.infer_node_datatype` input type is evaluated and an exception raised if it's not as expected.
If the graph is not sorted an new tensors have been created this can fail.

A warning or an exception should be raised

**Comment by maltanar** [comment]
In many places in the FINN codebase we make the assumption that the graph is topologically sorted, just like the ONNX standard dictates. So a non-sorted graph as input to transformations (except the sorting transformation) isn't valid.

The real issue here is when/if transformations result in unsorted graphs, and if we want to allow that the easy way out is making graph sorting automatic after any transformation is applied, i.e. https://github.com/Xilinx/finn/issues/102
