### ISSUE TITLE
Testfile input_0.pb can't be loaded via get_data() instruction in tfc_end2end_example.ipynb notebook

### ISSUE THREAD

**Issue by chhait07** [Xilinx/finn#269]
Hi,
on executing line `raw_i = get_data("finn", "data/onnx/mnist-conv/test_data_set_0/input_0.pb")` in the `tfc_end2end_example.ipynb` notebook nothing is received. See the following screenshot.
![Issue](https://user-images.githubusercontent.com/78212618/106275384-082f3680-6236-11eb-9e13-7e41e7147f4b.png)

I'm using Ubuntu 18.4

**Comment by jalezeta** [comment]
Hi @chhait07! This is caused because the "input_0.pb" dataset was moved into the "finn-base" repository. You can read the file directly from the finn-base folder which is mounted in the Docker container.  You have to replace the way _raw_i_ reads the dataset. The following workaround seems to work:
`raw_i = open('/workspace/finn-base/src/finn/data/onnx/mnist-conv/test_data_set_0/input_0.pb','rb').read()`
