### ISSUE TITLE
IndexError: list index (2) out of range

### ISSUE THREAD

**Issue by xpww** [Xilinx/finn#408]
when i run tfc_end2end_verification ,it put this error

can someone help me?I am a novice in this field.
 
![77](https://user-images.githubusercontent.com/88141892/138741060-9cca6194-2158-4ee3-a07d-fd8516af98bf.png)

**Comment by mmrahorovic** [comment]
Hi @xpww , apologies for the late notice, but this will be fixed in the upcoming release.
But for a quick fix, you can change the index from `2` to `1` and it should work.
Also, each time the computed output is checked against the golden output, you should replace `output_golden` with `np.where(output_golden[0]==np.amax(output_golden[0])`.

Please let us know if you encounter any other issues!

**Comment by auphelia** [comment]
Hi @xpww, the new release is out so the issue should be resolved. I will close the issue for now, if you are still facing problems, let us know.
