### ISSUE TITLE
%Error: .../code_gen_ipgen_MatrixVectorActivation_1_vtapif2w/memblock_sim_0.dat:17: $readmem file ended before specified ending-address

### ISSUE THREAD

**Issue by mgehre-amd** [Xilinx/finn#667]
## Prerequisites
Please make sure to check off these prerequisites before submitting a bug report.
- [x] Test that the bug appears on the current version of the dev-branch. Make sure to include the commit hash of the commit you checked out.
- [x] Check that the issue hasn't already been reported, by checking the currently open issues.
- [x] If there are steps to reproduce the problem, make sure to write them down below.
- [x] If relevant, please include the ONNX files, which were created directly before and/or after the bug.

## Quick summary
```
Running step: step_mobilenet_streamline [1/12]
Running step: step_mobilenet_lower_convs [2/12]
Running step: step_mobilenet_convert_to_hls_layers_separate_th [3/12]
Running step: step_create_dataflow_partition [4/12]
Running step: step_target_fps_parallelization [5/12]
Running step: step_generate_estimate_reports [6/12]
Running step: step_hls_codegen [7/12]
Running step: step_hls_ipgen [8/12]
Running step: step_set_fifo_depths [9/12]
Running step: step_create_stitched_ip [10/12]
Running step: step_measure_rtlsim_performance [11/12]
%Error: /scratch/tmp/finn/code_gen_ipgen_MatrixVectorActivation_1_5f_rpjp5/memblock_sim_0.dat:17: $readmem file ended before specified ending-address
Aborting...
```

## Details
Please add to the following sections to describe the bug as accurately as possible.

### Steps to Reproduce
Add what needs to be done to reproduce the bug. Add code examples where useful
and make sure to include the resulting ONNX files, and the commit hash you are working on.

1. Clone the FINN repository
2. Checkout the dev branch, with commit hash: 09bec2fe
3. Checkout finn-examples from https://github.com/mgehre-amd/finn-examples/tree/matthias.bug_ending-address
(This is mobilenet-v1, but using step_target_fps_parallelization instead of step_apply_folding_config and enabling step_measure_rtlsim_performance )
5. Start the docker container with the command: ./run-docker.sh build_custom ../finn-examples/build/mobilenet-v1

### Expected behavior
No error

### Actual behavior
Running step: step_measure_rtlsim_performance [11/12]
%Error: /scratch/tmp/finn/code_gen_ipgen_MatrixVectorActivation_1_5f_rpjp5/memblock_sim_0.dat:17: $readmem file ended before specified ending-address

**Comment by auphelia** [comment]
Hi @mgehre-amd , Thank you for raising this issue! 

The problem is coming from the setting you pass to the builder: 

When [`USE_FIXED_FOLDING`](https://github.com/mgehre-amd/finn-examples/blob/matthias.bug_ending-address/build/mobilenet-v1/build.py#L84)  is set to `FALSE` like it is is done in your code, you execute the automatic folding transformation with `step_target_fps_parallelization`. But when calling `step_set_fifo_depths` with [`auto_fifo_depths=False`](https://github.com/mgehre-amd/finn-examples/blob/matthias.bug_ending-address/build/mobilenet-v1/build.py#L143) and passing a folding_config_file, the values get overwritten, see [here](https://github.com/Xilinx/finn/blob/main/src/finn/builder/build_dataflow_steps.py#L559). Since the config .json is written in a way that it uses node names, it can lead to buggy behavior. 
To make your code work you need to set `auto_fifo_depths=True` when trying to use `USE_FIXED_FOLDING=False`.
