### ISSUE TITLE
Throughput test result for clock

### ISSUE THREAD

**Issue by smtalds** [Xilinx/finn#876]
Hi , i build the confing like this settings : 
![image](https://github.com/Xilinx/finn/assets/59387657/44fdf342-9580-4d4a-8508-a9f9d6489bd6)
and my troughput results is showing clock 100MHz.
![image](https://github.com/Xilinx/finn/assets/59387657/2ba4775a-d394-44bd-9f6b-de20ad7d53d6)
But I opened the vivado project , clock is 200MHz. So its true. Is it a bug or problem ?
![image](https://github.com/Xilinx/finn/assets/59387657/921ae88b-145f-4728-b41b-dc336bede2d2) Btw , I have so much TNS. What is the problem ? How can i solve this problem ?  Thanks for answer.
![image](https://github.com/Xilinx/finn/assets/59387657/a94f9b48-395b-4d60-9544-ebfa57766113)

**Comment by fpjentzsch** [comment]
Hi,

the design was indeed synthesized with a 200 MHz clock because you set `synth_clk_period_ns=5.0` in the build config.

The throughput test shows 100 MHz, because you did not specify a clock with the `fclk_mhz` argument when initializing the `FINNExampleOverlay`, so it defaults to 100 MHz. The PYNQ driver can reconfigure the PL clock generator at runtime by changing the divisors, and this clock configuration is performed every time you load the overlay/bitstream by instantiating the `FINNExampleOverlay`.

I hope this helps, maybe you can try to synthesize for 100 MHz to improve your timing.

**Comment by smtalds** [comment]
@fpjentzsch  Ah , I was thinking `FINNExampleOverlay` is get `fclk` from bitfile. It was my fault :/ Thanks for answering.
